<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ATAS.Indicators">
      <HintPath>$(APPDATA)\ATAS\ATAS.Indicators.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
